apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: api-service-account
      containers:
        - name: api
          image: school-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql://postgres:postgres@db:5432/school_db
          volumeMounts:
            - name: api-storage
              mountPath: /data
            - name: shared-storage
              mountPath: /shared
      volumes:
        - name: api-storage
          persistentVolumeClaim:
            claimName: api-pvc
        - name: shared-storage
          persistentVolumeClaim:
            claimName: shared-pvc 