apiVersion: v1
kind: Pod
metadata:
  name: task-${TASK_NAME}-${STUDENT_NAME}-${TIMESTAMP}
  labels:
    app: task
    task: ${TASK_NAME}
    student: ${STUDENT_NAME}
spec:
  containers:
    - name: task
      image: school-task:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: TASK_NAME
          value: ${TASK_NAME}
        - name: STUDENT_NAME
          value: ${STUDENT_NAME}
        - name: TEACHER_SCRIPT
          value: /app/scripts/teacher_script.py
        - name: STUDENT_SCRIPT
          value: /app/scripts/student_script.py
        - name: OUTPUT_DIR
          value: /app/output
      volumeMounts:
        - name: task-scripts
          mountPath: /app/scripts
        - name: task-output
          mountPath: /app/output
  volumes:
    - name: task-scripts
      persistentVolumeClaim:
        claimName: task-pvc
    - name: task-output
      persistentVolumeClaim:
        claimName: task-pvc
  restartPolicy: Never 